[mypy]
# Игнорировать ошибки импорта для всех библиотек, где нет типов
ignore_missing_imports = True

# Разрешить не типизировать функции, если это слишком сложно для начала
disallow_untyped_defs = False