# Generated by Django 6.0.6 on 2026-07-09 10:12

from django.db import migrations, models
from typing import Any

class Migration(migrations.Migration):

    initial = True

    dependencies: list[Any] = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Сообщение пациентов",
                "verbose_name_plural": "Сообщения пациентов",
            },
        ),
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=55)),
                ("title_ru", models.CharField(max_length=55, null=True)),
                ("title_en", models.CharField(max_length=55, null=True)),
                ("content", models.TextField(max_length=5000)),
                ("content_ru", models.TextField(max_length=5000, null=True)),
                ("content_en", models.TextField(max_length=5000, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="pages_content/"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=55, unique=True)),
            ],
            options={
                "verbose_name": "Страница",
                "verbose_name_plural": "Страницы",
            },
        ),
    ]
