# Generated by Django 6.0.6 on 2026-07-09 10:12

from typing import Any

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[Any] = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=55)),
                ("title_ru", models.CharField(max_length=55, null=True)),
                ("title_en", models.CharField(max_length=55, null=True)),
                ("content", models.TextField(max_length=1255)),
                ("content_ru", models.TextField(max_length=1255, null=True)),
                ("content_en", models.TextField(max_length=1255, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="blog/")),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
