# Generated by Django 6.0.6 on 2026-07-09 10:12

from typing import Any

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[Any] = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Дата и время записи")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("confirmed", "Подтверждена"),
                            ("completed", "Завершена"),
                        ],
                        default="created",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "barcode_id",
                    models.UUIDField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
        migrations.CreateModel(
            name="DiagnosticResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_text",
                    models.TextField(max_length=255, verbose_name="Текст результата"),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Загрузите PDF анализов",
                        upload_to="m/",
                        verbose_name="PDF анализов",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время загрузки анализов"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("in progress", "В работе"), ("ready", "Готово")],
                        verbose_name="Статус результата",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат",
                "verbose_name_plural": "Результаты",
            },
        ),
    ]
