# Generated by Django 6.0.6 on 2026-07-09 10:12

from django.db import migrations, models
from typing import Any


class Migration(migrations.Migration):

    initial = True

    dependencies: list[Any] = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=55, verbose_name="Название услуги"),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=55, null=True, verbose_name="Название услуги"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=55, null=True, verbose_name="Название услуги"
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=255, verbose_name="Описание услуги"),
                ),
                (
                    "description_ru",
                    models.TextField(
                        max_length=255, null=True, verbose_name="Описание услуги"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        max_length=255, null=True, verbose_name="Описание услуги"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Цена услуги")),
                ("duration", models.DurationField(verbose_name="Продолжительность")),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("lab_test", "Лабораторный анализ"),
                            ("doctor_appointment", "Запись к врачу"),
                        ],
                        verbose_name="Тип услуги",
                    ),
                ),
                (
                    "service_type_ru",
                    models.CharField(
                        choices=[
                            ("lab_test", "Лабораторный анализ"),
                            ("doctor_appointment", "Запись к врачу"),
                        ],
                        null=True,
                        verbose_name="Тип услуги",
                    ),
                ),
                (
                    "service_type_en",
                    models.CharField(
                        choices=[
                            ("lab_test", "Лабораторный анализ"),
                            ("doctor_appointment", "Запись к врачу"),
                        ],
                        null=True,
                        verbose_name="Тип услуги",
                    ),
                ),
                (
                    "completion_date",
                    models.CharField(max_length=55, verbose_name="Срок выполнения"),
                ),
                (
                    "rules",
                    models.CharField(
                        choices=[
                            ("On an empty stomach", "Натощак"),
                            ("Don't eat for two hours", "Не есть за два часа"),
                            ("No rules", "Нет ограничений"),
                        ],
                        verbose_name="Правило подготовки для сдачи анализа",
                    ),
                ),
                (
                    "rules_ru",
                    models.CharField(
                        choices=[
                            ("On an empty stomach", "Натощак"),
                            ("Don't eat for two hours", "Не есть за два часа"),
                            ("No rules", "Нет ограничений"),
                        ],
                        null=True,
                        verbose_name="Правило подготовки для сдачи анализа",
                    ),
                ),
                (
                    "rules_en",
                    models.CharField(
                        choices=[
                            ("On an empty stomach", "Натощак"),
                            ("Don't eat for two hours", "Не есть за два часа"),
                            ("No rules", "Нет ограничений"),
                        ],
                        null=True,
                        verbose_name="Правило подготовки для сдачи анализа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
    ]
